### ISSUE TITLE
Método  buscar en árbol n-ario

### ISSUE THREAD

**Issue by javierri** [javierri/Arbol-Binario#3]
En el método buscar de la clase n-arios hay un error.. ¿ Cuál será  ?

```
def buscar (self, valor):

            if (self.__buscar(valor, self.__raiz.hijos, 0) != None):
                    return True
            return False
```

**Comment by rotsen254** [comment]
Buenas tarde profesor el error que tiene ese codigo es que cuando se quiere buscar el valor que se encuentra en la raíz el programa dice que no lo encuentra es decir, si la raiz del árbol es la letra "E" y se trata de buscar a esta misma el programa devuelve False siendo esta respuesta incorrecta, es posible que el error se produzca xq el programa no evalúa  el valor que se le envía por parametro con la raíz del árbol, solo lo evalúa con los hijos del arbol

**Comment by javierri** [comment]
Listo .. ese es el error !!
Muchas gracias Nestor..

**Comment by javierri** [comment]
A ver otro compañero que sea Nestor que coloque el código corregido en este foro ...

**Comment by rotsen254** [comment]
lo coloco yo u otra persona?

**Comment by rotsen254** [comment]
#Este es el código corregido profesor
def buscar (self, valor):
			if(self.__raiz.info == valor):
				return True
			if (self.__buscar(valor, self.__raiz.hijos, 0) != None):
				return True
			return False

**Comment by javierri** [comment]
Otra persona . !

**Comment by mariacolmenares** [comment]
```
codigo corregido
def buscar (self, valor):
           if (self.__raiz.info == valor):
                   return True
           if (self.__buscar(valor, self.__raiz.hijos, 0) != None):
                    return True
           return False
```

**Comment by javierri** [comment]
Muy bien @mariacolmenares 
Pero eso no funciona .. tiene errores de indentacion.. hay una opción que te permite ingresar el código tal como yo lo coloque al inicio y respetar las indentaciones.. es <> .. inténtalo.

**Comment by javierri** [comment]
Ahh.. y te ganaste un punto (en el examen) no tanto por responder el foro sino porque hiciste el cambio en el código de arboln.py y eso se llama **iniciativa** .

**Comment by mariacolmenares** [comment]
codigo corregido
<def buscar (self, valor):
           if (self.__raiz.info == valor):
                         return True
           if (self.__buscar(valor, self.__raiz.hijos, 0) != None):
                       return True
           return False >

**Comment by mariacolmenares** [comment]
Ok profesor , tratare de modificar el código para que se muestre las indentaciones ...

**Comment by javierri** [comment]
Cuando escribes tu nota en el borde superior del cuadro gris, donde ves letras como "A B i " <> .."

Que haces seleccionas tu codigo.. presionas <> y luego lo indentas, y puedes verificarlo en la pestaña de preview antes de enviar el mensaje.
